### PR TITLE
OpenVPN server TCP support.

### PR DESCRIPTION
**Pull request by elpatopedraza**

### CODE REVIEW

**Review by bedro0 — APPROVED** [review]
I was gonna implement something like this, but you did it better than I ever could. 

Client config file is not regenerated if persistent volume is used, so I would add a note reminding users to change the local client config file, if they changed protocol on an existing deployment.

**Comment by fantinialex** [comment]
+1

**Comment by CyberAustin** [comment]
So, is this going to be merged?

**Comment by alekslitvinenk** [comment]
Hi everybody, we will merge this PR ASAP

**Pull request merged**
