### PR TITLE
Allow to specify custom CLIENT_ID and PORT

### PR DESCRIPTION
**Pull request by ates**

### CODE REVIEW

**Comment by alekslitvinenk** [comment]
Thanks a lot for your contribution! I'll review it in a short while and merge

**Comment by LivingWithHippos** [comment]
$CLIENT_ID should be passed as argument to genclient.sh and then functions.sh , not as an env variable, something like `CLIENT_PATH="$(createConfig $2)"` to pass the second argument  to createConfig and then 


```shell
function createConfig() {
    cd "$APP_PERSIST_DIR"

    if [ -z "$1" ]; then
        CLIENT_ID="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
   else
        CLIENT_ID="$1"
    fi
```

this way you can generate a cert with `genclient.sh o 123` with a client id 123 (for backward compatibility the client id should be the 2nd argument)

**Comment by alekslitvinenk** [comment]
Another problem is we cannot guarantee uniqueness of said CLIENT_ID, so the api should return ether a config or failure.
Also, depending on the use-case there's always a possibility to grab generated id directly from config (the last line):
Screenshot 2022-08-15 at 12 53 49

I keep thinking on a graceful solution of the problem

**Comment by alekslitvinenk** [comment]
The original issue of this PR was resolved in PR #171 

This one can be closed

**Pull request closed without merging**
